on:
  pull_request_review:
    types: [labeled]

jobs:
  approved_job:
    if: github.event.pull_request.labels == 'carai'
    runs-on: ubuntu-latest
    steps:
    - run: echo "This PR was labeled carai"
