on:
  pull_request:
   # types: [labeled]
    branches:
      - 'main'

jobs:
  approved_job:
    if: contains (github.event.pull_request.labels.*.name, 'carai')
    runs-on: ubuntu-latest
    steps:
    - run: echo "This PR was labeled carai"
